[project]
name = "odc-dscache"
dynamic = ["version"]
description = "ODC Dataset File Cache"
authors = [
    {name = "Open Data Cube", email = "earth.observation@ga.gov.au"},
]
requires-python = ">=3.10"
readme = "README.md"
license = "Apache-2.0"
dependencies = [
    "click",
    "datacube>=1.9,<1.10.0",
    "lmdb",
    "odc-geo",
    "pandas",
    "psycopg2",
    "toolz",
    "zstandard",
]

[project.urls]
Homepage = "https://github.com/opendatacube/odc-dscache/"

[project.optional-dependencies]
dev = [
    "pytest",
]

[project.scripts]
dstiler = "odc.dscache.apps.dstiler:cli"
slurpy = "odc.dscache.apps.slurpy:cli"

[tool.setuptools.packages.find]
exclude = ["tests"]
include = ["odc*"]

[build-system]
requires = ["setuptools>=69", "setuptools_scm[toml]>=8"]
build-backend = "setuptools.build_meta"

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true
allow_redefinition = true

[tool.coverage.run]
omit = [
  "tests/*"
]


[tool.pylint.messages_control]

max-line-length = 120

disable = [
  "missing-function-docstring",
  "missing-module-docstring",
  "too-many-return-statements",
  "too-many-arguments",
  "invalid-name",
  "fixme",
  "R0801",
]

[tool.setuptools_scm]
write_to = "odc/dscache/_version.py"
fallback_version = "1.9.1.dev0"
